---
- name: Set OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- include: install_{{ ansible_os_family | lower }}.yml

- include: configure.yml

# This is initial install, so we stop it and reset it so our configs can be
# applied during an initial start.
- name: Stop RabbitMQ if just installed and already running
  command: rabbitmqctl stop_app
  when: _rabbitmq_deb_check.rc == 1 and _rabbitmq_run_check.rc == 0

- name: Reset RabbitMQ if just installed and already running
  command: rabbitmqctl reset
  when: _rabbitmq_deb_check.rc == 1 and _rabbitmq_run_check.rc == 0

- name: Ensure RabbitMQ is enabled and running
  service:
    name: "{{ rabbitmq_service }}"
    enabled: yes
    state: started
    daemon_reload: yes
