---
- name: Converge
  hosts: all
  become: yes
  roles:
    - role: ../../..
      rabbitmq_install_custom_erlang: false
      rabbitmq_erlang_cookie: sekrit
      rabbitmq_cluster_nodes:
        - host: molecule_rabbit1
        - host: molecule_rabbit2
      rabbitmq_users:
        joe: {}
